# Generated by Django 4.0.3 on 2022-03-31 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NAME', models.CharField(max_length=300)),
                ('ADDRESS', models.TextField(max_length=300)),
                ('NUMBER', models.IntegerField()),
                ('EMAIL', models.EmailField(max_length=254)),
            ],
        ),
    ]
