# Generated by Django 4.0.3 on 2022-03-31 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='Idno',
            field=models.IntegerField(default=0),
        ),
    ]
